export const AppIcons = {
  appLogo: require('../assets/images/logobackground.png'),
  completed: require('../assets/images/completed.png'),
  marker: require('../assets/images/maker.png'),
  service: require('../assets/images/service.png'),
  setLocation: require('../assets/images/setLocation.png'),
  location: require('../assets/images/location.png'),
  notification: require('../assets/images/notification.png'),
  correct: require('../assets/images/correct.png'),
  bookService: require('../assets/images/bookServices.png'),
  searchService: require('../assets/images/searchService.png'),
  menu: require('../assets/images/menu.png'),
  salon: require('../assets/images/salon.png'),
  barber: require('../assets/images/barber.png'),
  nail: require('../assets/images/nail.png'),
  all: require('../assets/images/all.png'),
  barber2: require('../assets/images/baber.jpeg'),
  user: require('../assets/images/user.png'),
  pickedUser: require('../assets/images/pickedUser.png'),
  bankCard: require('../assets/images/bankCard.png'),
  facebook: require('../assets/images/facebook.png'),
  google: require('../assets/images/google.png'),
  splash: require('../assets/images/splash.png'),
  logo2: require('../assets/images/logo2.png'),
  all2: require('../assets/images/all2.png'),
};
